In [1]:
import numpy as np
import scipy

In [6]:
array1d = np.array([0, 2, 4, 6, 8])
print array1d

[0 2 4 6 8]


In [9]:
array2d = np.array([[1,2,3],[4,5,6]])
print array2d

[[1 2 3]
 [4 5 6]]


In [10]:
print type(array1d)

<type 'numpy.ndarray'>


In [11]:
print np.shape(array1d)

(5,)


In [12]:
print np.shape(array2d)

(2, 3)


In [15]:
print array1d[0]

0


In [18]:
print array2d[1,2]

6


In [17]:
print array2d[1][2]

6


In [20]:
print array1d[1:]

[2 4 6 8]


In [25]:
print array2d[1,:1]

[4]


In [26]:
print array2d[1,1:]

[5 6]
