In [1]:
import numpy as np
import scipy

In [6]:
array1d = np.array([0, 2, 4, 6, 8])
print array1d

[0 2 4 6 8]


In [9]:
array2d = np.array([[1,2,3],[4,5,6]])
print array2d

[[1 2 3]
 [4 5 6]]


In [10]:
print type(array1d)

<type 'numpy.ndarray'>


In [11]:
print np.shape(array1d)

(5,)


In [12]:
print np.shape(array2d)

(2, 3)


In [15]:
print array1d[0]

0


In [18]:
print array2d[1,2]

6


In [17]:
print array2d[1][2]

6


In [20]:
print array1d[1:]

[2 4 6 8]


In [25]:
print array2d[1,:1]

[4]


In [26]:
print array2d[1,1:]

[5 6]


In [29]:
new2darray = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
print new2darray

(3, 5)


In [30]:
print np.shape(new2darray)

(3, 5)


In [34]:
# Integer Array Indexing
newSubarray = new2darray[[1,0,2],[2,4,3]] #for elements with indices (1,2) (0,4), (2,3)
print newSubarray

[ 7  4 13]


In [36]:
# Boolean Array Indexing
print new2darray[new2darray>10]

[11 12 13 14]


In [38]:
print new2darray>10

[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]]


In [45]:
print np.ones([5,5], dtype=int)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [47]:
print np.zeros([5,5], dtype=int)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [48]:
print np.full(np.shape(new2darray), 5)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [49]:
print np.eye(5)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [50]:
print np.random.random([5,5])

[[ 0.94911073  0.78942732  0.78943462  0.39993114  0.06719278]
 [ 0.74790594  0.85918025  0.86715813  0.10502031  0.48802841]
 [ 0.63243854  0.8594374   0.70903452  0.05568564  0.90813181]
 [ 0.97685519  0.65328326  0.4962829   0.67328346  0.6286543 ]
 [ 0.12615931  0.57617391  0.76738164  0.76354343  0.4834579 ]]


In [53]:
transposeArray = np.transpose(new2darray)
print transposeArray

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [54]:
print np.shape(transposeArray)

(5, 3)


In [58]:
reshapedArray = np.reshape(new2darray, [1,15]) #This works as long as total no. of elements remain the same
print reshapedArray

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


In [57]:
print np.shape(reshapedArray)

(1, 15)


In [59]:
reshapedArray = np.reshape(new2darray, [15,1])
print reshapedArray

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]


In [60]:
print np.shape(reshapedArray)

(15, 1)
